ADD_SCENE(desktop_settings, start, Start)
ADD_SCENE(desktop_settings, favorite, Favorite)
ADD_SCENE(desktop_settings, pin_menu, PinMenu)

ADD_SCENE(desktop_settings, pin_auth, PinAuth)
ADD_SCENE(desktop_settings, pin_disable, PinDisable)
ADD_SCENE(desktop_settings, pin_setup, PinSetup)
ADD_SCENE(desktop_settings, pin_setup_howto, PinSetupHowto)
ADD_SCENE(desktop_settings, pin_setup_howto2, PinSetupHowto2)
ADD_SCENE(desktop_settings, pin_setup_done, PinSetupDone)

ADD_SCENE(desktop_settings, change_name, ChangeName)
ADD_SCENE(desktop_settings, name_popup, NamePopup)

ADD_SCENE(desktop_settings, wallpaper_setup, WallpaperSetup)
ADD_SCENE(desktop_settings, rgb_settings, RgbSettings)
ADD_SCENE(desktop_settings, pin_error, PinError)
ADD_SCENE(desktop_settings, disconnect_services, DisconnectServices)
ADD_SCENE(desktop_settings, lock_display, LockDisplay)
ADD_SCENE(desktop_settings, main_menu, MainMenu)
ADD_SCENE(desktop_settings, main_menu_actions, MainMenuActions)
ADD_SCENE(desktop_settings, main_menu_rename, MainMenuRename)
ADD_SCENE(desktop_settings, vgm_options, VgmOptions)
ADD_SCENE(desktop_settings, alarm_clock, AlarmClock)
ADD_SCENE(desktop_settings, alarm_edit, AlarmEdit)
ADD_SCENE(desktop_settings, menu_style, MenuStyle)
